theme: jekyll-theme-cayman

title: tree-ware
description: Software that uses trees as a fundamental unit of data. <a href="https://en.wikipedia.org/wiki/Turtles_all_the_way_down">It's trees all the way down</a>.
